"""Build a small original, local CC0 resource set. No network or paid API."""
from __future__ import annotations

from pathlib import Path
import math
import subprocess
import sys
import tempfile
import wave

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from reelkit.motion_resources import import_resource, ensure_resource_dirs

SVG = {
    "arrow-forward": '<path d="M4 12h16m-7-7 7 7-7 7"/>',
    "check-mark": '<path d="m4 12 5 5L20 6"/>',
    "notification-bell": '<path d="M6 17h12l-2-3V9a4 4 0 0 0-8 0v5l-2 3Zm4 3h4"/>',
    "progress-ring": '<circle cx="12" cy="12" r="9"/><path d="M12 3a9 9 0 0 1 9 9"/>',
    "flow-node": '<circle cx="5" cy="12" r="2"/><circle cx="19" cy="5" r="2"/><circle cx="19" cy="19" r="2"/><path d="M7 12h6l4-7m-4 7 4 7"/>',
}
SFX = {
    "soft-tap": (620, .11, 28),
    "ui-pop": (480, .16, 19),
    "soft-impact": (150, .23, 17),
    "short-whoosh": (300, .29, 10),
    "swipe": (780, .18, 16),
}


def build() -> None:
    ensure_resource_dirs()
    with tempfile.TemporaryDirectory(prefix="motion-resources-", dir=ROOT / "projects") as tmp:
        folder = Path(tmp)
        for ident, shape in SVG.items():
            source = folder / f"{ident}.svg"
            source.write_text(
                '<svg xmlns="http://www.w3.org/2000/svg" width="96" height="96" viewBox="0 0 24 24" '
                'fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" '
                f'stroke-linejoin="round">{shape}</svg>', encoding="utf-8")
            scenes = ["notification"] if ident == "notification-bell" else (
                ["steps", "diagram"] if ident in ("arrow-forward", "flow-node") else ["progress"] if ident == "progress-ring" else ["cta"])
            import_resource(source, ident=ident, category="icons", tags=ident.split("-"),
                            license="CC0-1.0", origin="Original geometry generated by scripts/build_starter_resources.py",
                            safety="approved", compatible_scenes=scenes, style_tags=["modern"],
                            preferred_use=["Small scene accent; preserve headline hierarchy"])
        rate = 48000
        for ident, (frequency, duration, decay) in SFX.items():
            source = folder / f"{ident}.wav"
            with wave.open(str(source), "wb") as output:
                output.setnchannels(1); output.setsampwidth(2); output.setframerate(rate)
                frames = bytearray()
                for i in range(round(rate * duration)):
                    t = i / rate
                    sweep = frequency * (1 + .18 * t / duration if "whoosh" in ident or ident == "swipe" else 1)
                    sample = int(6500 * math.sin(2 * math.pi * sweep * t) * math.exp(-decay * t))
                    frames += sample.to_bytes(2, "little", signed=True)
                output.writeframes(frames)
            import_resource(source, ident=ident, category="sfx/" + {
                "soft-tap": "clicks", "ui-pop": "pops", "soft-impact": "impacts",
                "short-whoosh": "whooshes", "swipe": "swipes"}[ident],
                tags=ident.split("-"), license="CC0-1.0",
                origin="Original synthetic transient generated by scripts/build_starter_resources.py",
                safety="approved", compatible_scenes=[], style_tags=["modern"])
        # Short alpha overlay plus the source PNG sequence demonstrate both supported paths.
        from PIL import Image, ImageDraw
        sequence = folder / "focus-ring-frames"
        sequence.mkdir()
        for i in range(30):
            im = Image.new("RGBA", (320, 320), (0, 0, 0, 0))
            draw = ImageDraw.Draw(im)
            radius = 45 + round(75 * i / 29)
            alpha = round(210 * (1 - i / 29))
            draw.ellipse((160-radius, 160-radius, 160+radius, 160+radius),
                         outline=(118, 221, 200, alpha), width=8)
            im.save(sequence / f"frame-{i:03}.png")
        import_resource(sequence, ident="focus-ring-sequence", category="image-sequences",
                        tags=["focus", "ring", "emphasis"], license="CC0-1.0",
                        origin="Original frames generated by scripts/build_starter_resources.py",
                        safety="approved", compatible_scenes=["statement", "notification"],
                        loopable=False, sequence_fps=30, style_tags=["modern"])
        webm = folder / "focus-ring-overlay.webm"
        subprocess.run(["ffmpeg", "-v", "error", "-y", "-framerate", "30", "-i",
                        str(sequence / "frame-%03d.png"), "-c:v", "libvpx-vp9", "-pix_fmt", "yuva420p",
                        "-auto-alt-ref", "0", "-b:v", "0", "-crf", "24", str(webm)], check=True)
        import_resource(webm, ident="focus-ring-overlay", category="video/alpha",
                        tags=["focus", "ring", "emphasis", "overlay"], license="CC0-1.0",
                        origin="Original transparent VP9 overlay generated by scripts/build_starter_resources.py",
                        safety="approved", compatible_scenes=["statement", "notification"],
                        loopable=True, style_tags=["modern"], safe_for_motion_only=True)
    print("Original starter resources are ready.")


if __name__ == "__main__":
    build()
