import type {Project} from '../engine/contracts';
export const fixture:Project={version:1,id:'Synthetic',frame:{width:1080,height:1920,fps:{num:30,den:1}},
  audio:{src:'',sha256:'0'.repeat(64),sampleRate:48000,sampleCount:288000,channels:2,codec:'pcm_s16le',durationSource:'decoded-samples'},
  events:{open:0,focus:144000},
  scenes:[{id:'intro',start:0,end:144000,narration:'Synthetic fixture, no speech',purpose:'definition',hierarchy:['token'],visualReason:'Introduce a persistent function',density:'low',uncertainty:[],source:'Authored synthetic fixture'},
    {id:'result',start:144000,end:288000,narration:'Synthetic fixture, no speech',purpose:'process',hierarchy:['token'],visualReason:'Carry the same object into another function',density:'low',uncertainty:[],source:'Authored synthetic fixture'}],
  objects:[{id:'token',kind:'function',label:'function',role:'primary',size:[.43,.1],direction:'ltr',depth:0,allowOverlap:['container'],
    initial:{x:.5,y:.38,scale:1,opacity:0,rotation:0,focus:0,owner:null}},
    {id:'container',kind:'container',label:'Higher-Order Function',role:'secondary',size:[.65,.23],direction:'ltr',depth:0,allowOverlap:['token'],
    initial:{x:.5,y:.58,scale:1,opacity:0,rotation:0,focus:0,owner:null}},
    {id:'title',kind:'text',label:'الدالة قيمة في JavaScript',role:'secondary',size:[.8,.12],direction:'rtl',depth:0,allowOverlap:[],scene:'intro',
    initial:{x:.5,y:.2,scale:1,opacity:1,rotation:0,focus:0,owner:null}}],
  motions:[{target:'token',at:0,duration:24000,to:{opacity:1},ease:'out',intent:'entrance'},
    {target:'container',at:{event:'focus',offset:0},duration:24000,to:{opacity:1},ease:'out',intent:'entrance'},
    {target:'token',at:{event:'focus',offset:24000},duration:48000,to:{y:.58,scale:.62,owner:'container',focus:1},ease:'smooth',intent:'move'}],
  camera:[{at:48000,duration:48000,kind:'push',target:'token',x:.5,y:.5,zoom:1.04,intensity:.4,ease:'smooth',settle:true},
    {at:120000,duration:24000,kind:'settle',x:.5,y:.5,zoom:1,intensity:1,ease:'smooth',settle:true}],
  transitions:[{from:'intro',to:'result',at:144000,duration:14400,kind:'carry',shared:['token'],reason:'The function keeps its identity'}],
  captions:[{id:'phrase1',start:0,end:140000,text:'هذا مثال اصطناعي: الدالة قيمة',direction:'rtl',status:'verified',source:'Synthetic timing'},
    {id:'phrase2',start:144000,end:288000,text:'نفس الدالة تنتقل إلى دالة أخرى',direction:'rtl',status:'verified',source:'Synthetic timing'}],
  resources:[],sfx:[],references:[],
  style:{id:'code-dragon-v1',palette:{background:'#0B1221',surface:'#0F172A',text:'#E2E8F0',muted:'#94A3B8',accent:'#FFB800'},
    fonts:{arabic:'Cairo',latin:'Inter',code:'JetBrains Mono'},fontFiles:[],radius:20,captionSize:48,motionEnergy:'balanced'},
  layout:{safeArea:[.078,.063,.844,.68],captionZone:[.09,.79,.82,.15],minimumText:28}};
